name: aws
author: hangs0908
description: "Use aws module in github actions"
inputs:
  AWS_REGION:
    description: "set aws region"
    required: true
    default: "ap-northeast-2"
  AWS_ROLE_TO_ASSUME:
    description: "set role to assume"
    required: true
    default: "GithubActions"

runs:
  using: composite
  steps:
    - name: Config AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}