name: slack
author: hangs0908
description: 'Use slack job in github actions'
inputs:
  DEPLOY_STEP_STATUS:
    description: "delpoy step status"
    required: true
    default: "success"
  ENVIRONMENT:
    description: "set environment"
    required: true
    default: "dev"
  SLACK_WEBHOOK_URL:
    description: "set slack url"
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: notify
      uses: slackapi/slack-github-action@v1.27.0
      shell: bash
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "message",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Environment : ${{ inputs.environment }}, Deploy Result : ${{ inputs.DEPLOY_STEP_STATUS }}, Repository : ${{ github.repository }}."
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
