name: slack
author: hangs0908
description: 'Use slack job in github actions'
inputs:
  PERSONAL_ACCESS_TOKEN:
    description: "set pat"
    required: true
    default: ""
  HEAD:
    description: "set head branch"
    required: true
    default: "release/v0.0.0"
  BASE:
    description: "set base branch"
    required: true
    default: "master"

runs:
  using: composite
  steps:
    - name: create branch
      shell: bash
      run: |
          git checkout -b ${{ inputs.HEAD }}
          git push origin ${{ inputs.HEAD }}
    - name: create pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.PERSONAL_ACCESS_TOKEN }}
      run: |
        gh pr create --base ${{ inputs.BASE }} --head ${{ inputs.HEAD }} --title "${{ inputs.HEAD }} -> ${{ inputs.BASE }}" \
        --body "release pr"