name: image-build
author: hangs0908
description: "Use image-build module in github actions"
inputs:
  REPOSITORY:
    description: "set aws ecr repository"
    required: true
    default: "my-app"

runs:
  using: composite
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      shell: bash
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG